TimeTable/TimeTable/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('management/', include('management.urls')),
    path('admin/', admin.site.urls),
]

TimeTable/management/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('student/', views.view_students, name='view_students'),
    path('student/<student_id>/', views.student, name='student'),
    path('course/<course_id>/', views.course, name='course'),
    path('student/<student_id>/timetable', views.studentTimeTable, name='studentTimeTable'),
    path('logout',views.logout,name='logout'),
    path('add-student/',views.StudentCreate.as_view(),name='add-student'),


]

TimeTable/management/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class IntegerRangeField(models.BigIntegerField):
    def __init__(self, verbose_name=None, name=None, min_value=None, max_value=None, **kwargs):
        self.min_value, self.max_value = min_value, max_value
        models.IntegerField.__init__(self, verbose_name, name, **kwargs)
    def formfield(self, **kwargs):
        defaults = {'min_value': self.min_value, 'max_value':self.max_value}
        defaults.update(kwargs)
        return super(IntegerRangeField, self).formfield(**defaults)

class Programme(models.Model):
    Type =  models.CharField(max_length=4)
    def __str__(self):
        return self.Type


class Department(models.Model):
    Name =  models.CharField(max_length=100)
    Department_Code = models.CharField(max_length=3, primary_key = True)
    def __str__(self):
        return self.Name

class Student(models.Model):
    Student_ID = IntegerRangeField(min_value=17101001,max_value=17109200, primary_key = True)
    Department =  models.ForeignKey(Department, on_delete=models.CASCADE)
    Programme =   models.ForeignKey(Programme, on_delete=models.CASCADE, default = None)
    Year = IntegerRangeField(min_value=1,max_value=4,default = 1)
    Semester = IntegerRangeField(min_value=1,max_value=8,default = 1)
    First_Name =  models.CharField(max_length=30)
    Middle_Name =  models.CharField(max_length=30,null=True,blank=True)
    Last_Name =  models.CharField(max_length=30)
    Address = models.CharField(max_length=30)
    City = models.CharField(max_length=30,default='Chandigarh')
    State = models.CharField(max_length=30,default='Chandigarh')
    Phone_Number = IntegerRangeField(min_value=1000000000,max_value=9999999999)
    Date_of_Birth = models.DateField()
    def get_absolute_url(self):
        return reverse('management:student', kwargs = {'student_id: self.Student_ID'})
    def __str__(self):
        return str(self.Student_ID) #+ " : " + self.First_Name + " "  + self.Last_Name

class Course(models.Model):
    Name =  models.CharField(max_length=100,primary_key = True)
    Department = models.ForeignKey(Department, on_delete=models.CASCADE)
    Course_Number = IntegerRangeField(min_value=101,max_value=999)
    Semester = IntegerRangeField(min_value=1,max_value=8,default = 1)
    Course_Credits = IntegerRangeField(min_value=1,max_value=4,default=4)
    def __str__(self):
        return  self.Department.Department_Code + str(self.Course_Number) #+ " : " + self.Name


class Teacher(models.Model):
    designation_choices = (('Prof.','Professor'),('Dr.','Doctor'),('Ass. Prof.','Associate Professor'))
    Designation = models.CharField(max_length = 15,choices = designation_choices, default = 'Prof.' )
    Faculty_ID = IntegerRangeField(min_value=1001,max_value=9999, primary_key = True)
    Department =  models.ForeignKey(Department, on_delete=models.CASCADE)
    First_Name =  models.CharField(max_length=30)
    Middle_Name =  models.CharField(max_length=30,null=True,blank=True)
    Last_Name =  models.CharField(max_length=30)
    Course = models.ForeignKey(Course, on_delete=models.CASCADE)
    Phone_Number = IntegerRangeField(min_value=1000000000,max_value=9999999999)

    def __str__(self):
        return self.Designation + " " + self.First_Name + " "  + self.Last_Name

class Venue(models.Model):
    type_choices = (('L','Lecture Hall'),('T','Tutorial Room'))
    Type = models.CharField(max_length=1,choices=type_choices,default = 'L')
    Number = IntegerRangeField(min_value=1,max_value=99, primary_key = True)
    Department = models.ForeignKey(Department, on_delete=models.CASCADE,default = None)
    def __str__(self):
        return self.Type + " "  + str(self.Number)

class Lecture(models.Model):
    time_slot_choices = (('1','9:00-10:00'),('2','10:00-11:00'),('3','11:00-12:00'),('4','12:00-1:00'),('5','2:00-3:00'),('6','3:00-4:00'),('7','4:00-5:00'))
    days_choices = (('1','Monday'),('2','Tuesday'),('3','Wednesday'),('4','Thursday'),('5','Friday'))
    Time_Slot = models.CharField(max_length=1,choices=time_slot_choices,default = '1')
    Day = models.CharField(max_length=1,choices=days_choices,default = '1')
    Course = models.ForeignKey(Course, on_delete=models.CASCADE)
    Venue = models.ForeignKey(Venue, on_delete=models.CASCADE)
    Teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.Course) + " : " + self.Course.Name + " : " + str(self.Teacher)

TimeTable/management/views.py
from django.shortcuts import render
from django.http import HttpResponse,Http404
from django.shortcuts import render
from .models import Student,Course,Lecture
#from django.template import loader
from django.views.generic.edit import CreateView

def index(request):
    #html = '<h1>Welcome to the Home Page!</h1><br>'
    #html += '<a href = "' + 'student/' + '">' + 'Students' + '</a><br>'
    all_courses = Course.objects.all()
    #template = loader.get_template('management/index.html')
    #context = {'all_courses' : all_courses}
    return render(request,'management/index.html',{'all_courses' : all_courses})
def logout(request):
    return render(request,'management/logout.html')

def view_students(request):
    all_studs = Student.objects.all()
    html = ''
    html += '<h1>List of Students enrolled :</h1><br>'
    for stud in all_studs:
        url = str(stud.Student_ID) + '/'
        html += '<a href = "' + url + '">' + stud.First_Name + " " + stud.Last_Name + '</a><br>'
    return HttpResponse(html)

def student(request,student_id):
    try:
        student = Student.objects.get(pk=student_id)
    except Student.DoesNotExist:
        raise Http404("Student does not exist")
    if student.Middle_Name == None:
        name = student.First_Name + " " + student.Last_Name
    else:
        name = student.First_Name + " " + student.Middle_Name + " " + student.Last_Name
    return render(request,'management/student.html',{'student' : student,'name' : name})
    #return #HttpResponse("<h2>Welcome to the Student Page! <br>" + str(student_id) + " </h2>")

def course(request,course_id):
    return HttpResponse("<h2>Welcome to the Course Page! <br>" + str(course_id) + " </h2>")

def studentTimeTable(request,student_id):
    try:
        student = Student.objects.get(pk=student_id)
    except Student.DoesNotExist:
        raise Http404("Student does not exist")
    all_courses = Course.objects.filter(Department = student.Department).filter(Semester = student.Semester).order_by('Course_Number')
    all_lectures = Lecture.objects.all()
    #for c in all_courses:
    #    all_lectures = Lecture.objects.filter(Course = c)
    all_lectures = all_lectures.order_by('Time_Slot')#.order_by('Day')
    all_lectures = all_lectures.order_by('Day')
    Mon_lectures = all_lectures.filter(Day=1)
    Tue_lectures = all_lectures.filter(Day=2)
    Wed_lectures = all_lectures.filter(Day=3)
    Thu_lectures = all_lectures.filter(Day=4)
    Fri_lectures = all_lectures.filter(Day=5)
    if student.Middle_Name == None:
        name = student.First_Name + " " + student.Last_Name
    else:
        name = student.First_Name + " " + student.Middle_Name + " " + student.Last_Name
    context = {'all_courses' : all_courses,'student' : student,'name' : name, 'all_lectures' : all_lectures, 'Mon_lectures' : Mon_lectures,'Tue_lectures' : Tue_lectures,'Wed_lectures' : Wed_lectures,'Thu_lectures' : Thu_lectures,'Fri_lectures' : Fri_lectures,}

    return render(request,'management/timetable.html',context)

class StudentCreate(CreateView):
    model = Student
    fields = ['Student_ID','Department','Programme','Year','Semester','First_Name','Middle_Name','Last_Name','Address','City','State','Phone_Number','Date_of_Birth']









# Create your views here.

TimeTable/management/templates/management/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%}{%endblock%}</title>
    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" type = "text/css" href="{% static 'management/style.css' %}"/>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Arvo' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Secular One' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Oldenburg' rel='stylesheet'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>


</head>

<body style="font-family:'Arvo'">
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" datatoggle="collapse" data-target="#topNavBar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/management/" style="font-family:'Arvo'">Home</a>
        <ul class="nav navbar-nav">
          <li class="">
             <a href="/management/add-student/"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Sign Up</a>
          </li>
          <li class="">
             <a href="#"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;Login</a>
          </li>
          <li class="">
             <a href="/management/logout"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout</a>
          </li>
        </ul>
        <div class="collapse navbar-collapse" id="topNavBar">

       </div>
      </div>
    </div>
  </nav>

{% block body %}
{% endblock %}
</body>
</html>

TimeTable/management/templates/management/colorizedTT.html
<div class="container">
   <H2 align = "center" style="color:red ; font-family: Poiret One;font-weight:bold; font-size: 60px ">Current Time Table</H2><BR>
  <table class="table">
    <tr>
    <th> TIME/DAYS
    </th>
    <th> 08:30 - 09:00 </th>
    <th> 09:00 - 09:30 </th>
    <th> 09:30 - 10:00 </th>
    <th> 10:00 - 10:30 </th>
    <th> 10:30 - 11:00 </th>
    <th> 11:00 - 11:30 </th>
    <th> 11:30 - 12:00 </th>
    <th> 12:00 - 12:30 </th>
    <th> 14:00 - 15:25 </th>
    <th> 15:30 - 16:55 </th>
    <th> 17:00 - 18:00 </th>
    <th> 17:30 - 19:00 </th>
   </tr>

    <tr class = "success">
    <th> MONDAY </th>
    <td> CS 207 </td>
    <td> CS 207 </td>
    <td> HS 101 </td>
    <td> HS 101 </td>
    <td> </td>
    <td> </td>
    <td> EE 101</td>
    <td> EE 101</td>
    <td> </td>
    <td> CS 213</td>
    <td> </td>
    <td> </td>

    </tr>
    <tr class = "danger">
    <th> TUESDAY </th>
    <td> EE 101</td>
    <td> EE 101</td>
    <td> CS 207</td>
    <td> CS 207</td>
    <td> HS 101</td>
    <td> HS 101</td>
    <td> </td>
    <td> </td>
    <td> CS 251</td>
    <td> CS 251 </td>
    <td> CS 251 </td>
    <td>  </td>
    </tr>


    <tr class="active">
    <th> WEDNESDAY </th>
    <td> </td>
    <td> </td>
    <td> GNR 401 </td>
    <td> GNR 401 </td>
    <td> GNR 401 </td>
    <td> CS 215 </td>
    <td> CS 215 </td>
    <td> CS 215 </td>
    <td> </td>
    <td> </td>
    <td> </td>

    <td> </td></tr>
    <tr class = "warning">

    <th> THURSDAY </th>
    <td> </td>
    <td> </td>
    <td>EE 101 </td>
    <td>EE 101  </td>
    <td>CS 207  </td>
    <td>CS 207 </td>
    <td>HS 101 </td>
    <td>HS 101 </td>
    <td> </td>
    <td> CS 213 </td>
    <td> </td>
    <td> </td>
    </tr>

    <tr class = "info">
    <th> FRIDAY </th>
    <td> </td>
    <td> </td>
    <td> GNR 401 </td>
    <td> GNR 401 </td>
    <td> GNR 401 </td>
    <td> CS 215 </td>
    <td> CS 215 </td>
    <td> CS 215 </td>
    <td> CS 293</td>
    <td> CS 293</td>
    <td>  </td>
    <td> EE 101  </td>
    </tr>
  </table>
</div>

TimeTable/management/templates/management/index.html
{% extends 'management/base.html' %}
{% block title%}Welcome{%endblock%}
{% block body %}
  <img src="/static/management/images/pec_seal.png" alt="HTML5 Icon" style="width:250px;height:250px;" class="center">
  <h1 align="center" >Welcome to PEC's Time Table Management System!</h1>
  <br>
  <br>
  <div class="container">


    <!-- data-toggle lets you display modal without any JavaScript -->
    <button class="center" type="button" class="btn btn-success" data-toggle="modal" data-target="#popUpWindow">Login</button>

    <div class="modal fade" id="popUpWindow">
        <div class="modal-dialog">
            <div class="modal-content">

                <!-- header -->
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h3 class="modal-title">Log In</h3>
                </div>

                <!-- body (form) -->
                <div class="modal-body">
                    <form role="form">
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Student ID">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" placeholder="Password">
                        </div>
                    </form>
                </div>

                <!-- button -->
                <div class="modal-footer">
                    <button class="btn btn-primary btn-block">Submit</button>
                </div>

            </div>
        </div>
    </div>

</div>
<div class="LI-profile-badge"  data-version="v1" data-size="medium" data-locale="en_US" data-type="vertical" data-theme="light" data-vanity="manpreet-singh-juneja-16809b170"><a class="LI-simple-link" href='https://in.linkedin.com/in/manpreet-singh-juneja-16809b170?trk=profile-badge'>Manpreet Singh Juneja</a></div>
  <!--<img src="/static/management/images/pec_seal.png" alt="HTML5 Icon" style="float:left;width:192px;height:192px;">
  <h3>List of Courses</h3>

    {% for course in all_courses %}
  <li> <a href = "/management/course/{{course}}/"> {{course}}: {{course.Name}} </a></li>
  {% endfor %}-->

{% endblock %}

TimeTable/management/templates/management/logout.html
{% extends 'management/base.html' %}
{% block title%}Welcome{%endblock%}
{% block body %}
  <img src="/static/management/images/pec_seal.png" alt="HTML5 Icon" style="width:250px;height:250px;" class="center">
  <h1 align="center" >Welcome to PEC's Time Table Management System!</h1><br>
  <h1 align="center" >You have successfully logged out.</h1>
  <!--<img src="/static/management/images/pec_seal.png" alt="HTML5 Icon" style="float:left;width:192px;height:192px;">
  <h3>List of Courses</h3>

    {% for course in all_courses %}
  <li> <a href = "/management/course/{{course}}/"> {{course}}: {{course.Name}} </a></li>
  {% endfor %}-->

{% endblock %}

TimeTable/management/templates/management/student.html
{% extends 'management/base.html' %}
{% block title%}Student Home{%endblock%}
{% block body %}
  <!--<img src="/static/management/images/PEC-Logo.png" alt="HTML5 Icon" style="float:right;">-->
  <ul>
  <h2 style="font-family: 'Secular One'">{{name}}</h2>
  <table class="table">
    <tbody>
    <tr>
      <td>Student ID</td>
      <td>{{student.Student_ID}}</td>
    </tr>
    <tr>
      <td>Programme</td>
      <td>{{student.Programme}}</td>
    </tr>
    <tr>
      <td>Year</td>
      <td>{{student.Year}}</td>
    </tr>
    <tr>
      <td>Branch</td>
      <td>{{student.Department}}</td>
    </tr>
    </tbody>
  </table>

  <!--<h3><a href = "/management/student/{{student.Student_ID}}/timetable">Show TimeTable</a></h3>-->
  <h3><a href = "{% url 'studentTimeTable' student.Student_ID %}">Show TimeTable</a></h3>
  </ul>
{% endblock %}

TimeTable/management/templates/management/student_form.html
{% extends 'management/base.html' %}
{% block title%}Welcome{%endblock%}
{% block body %}

  <!--<img src="/static/management/images/pec_seal.png" alt="HTML5 Icon" style="float:left;width:192px;height:192px;">
  <h3>List of Courses</h3>

    {% for course in all_courses %}
  <li> <a href = "/management/course/{{course}}/"> {{course}}: {{course.Name}} </a></li>
  {% endfor %}-->

{% endblock %}

TimeTable/management/templates/management/timetable.html
{% extends 'management/base.html' %}
{% block title%}Student TimeTable{%endblock%}
{% block body %}
  <img src="/static/management/images/PEC-Logo.png" alt="HTML5 Icon" style="float:right;">
  <ul>

  <h1>Welcome to the PEC TimeTable Management System!</h1>

  <h2>{{name}}</h2>
  <h4>Student ID : {{student.Student_ID}}</h4>
  <h4>Programme  : {{student.Programme}}</h4>
  <h4>Year       : {{student.Year}}</h4>
  <h4>Branch     : {{student.Department}}</h4>


  <h3><a href = "/management/student/{{student.Student_ID}}/">Hide TimeTable</a></h3>
  <h1>Time Table</h1>

  <table class="table">

  <thead>
    <tr>
      <th>Day</th>
      <th>Time Slot</th>
      <th>Course</th>
      <th>Venue</th>
      <th>Taught By</th>
    </tr>
    </thead>
    <tbody>
      {% for lect in all_lectures %}
      <tr>
        <td>{{lect.get_Day_display}}</td>
        <td>{{lect.get_Time_Slot_display}}</td>
        <td>{{lect.Course.Name}}</td>
        <td>{{lect.Venue}}</td>
        <td>{{lect.Teacher.Designation}} {{lect.Teacher.First_Name}} {{lect.Teacher.Last_Name}}</td>
      </tr>
      {% endfor %}
    </tbody>

  </table>

  </ul>
{% endblock %}

TimeTable/management/templates/management/timetable1.html
{% extends 'management/base.html' %}
{% block title%}Student TimeTable{%endblock%}
{% block body %}
  <h1>Welcome to the PEC TimeTable Management System!</h1>

  <h2>{{name}}</h2>
  <h4>Student ID : {{student.Student_ID}}</h4>
  <h4>Programme  : {{student.Programme}}</h4>
  <h4>Year       : {{student.Year}}</h4>
  <h4>Branch     : {{student.Department}}</h4>

  <ul>
  <h3><a href = "/management/student/{{student.Student_ID}}/">Hide TimeTable</a></h3>
  {% for lect in all_lectures %}
  <!--<li><pre>{{lect.get_Day_display}}</pre>{{lect.get_Time_Slot_display}} | {{lect.Course.Name}} | {{lect.Venue}} | {{lect.Teacher.get_Designation_display}} {{lect.Teacher.First_Name}} {{lect.Teacher.Last_Name}}</li>-->
  {% endfor %}
<h1>Time Table</h1>
  <h4>Monday</h4>
  {% for lect in Mon_lectures %}
  <li>{{lect.get_Time_Slot_display}} | {{lect.Course.Name}} | {{lect.Venue}} | {{lect.Teacher.Designation}} {{lect.Teacher.First_Name}} {{lect.Teacher.Last_Name}}</li>
  {% endfor %}
  <h4>Tuesday</h4>
  {% for lect in Tue_lectures %}
  <li>{{lect.get_Time_Slot_display}} | {{lect.Course.Name}} | {{lect.Venue}} | {{lect.Teacher.Designation}} {{lect.Teacher.First_Name}} {{lect.Teacher.Last_Name}}</li>
  {% endfor %}
  <h4>Wednesday</h4>
  {% for lect in Wed_lectures %}
  <li>{{lect.get_Time_Slot_display}} | {{lect.Course.Name}} | {{lect.Venue}} | {{lect.Teacher.Designation}} {{lect.Teacher.First_Name}} {{lect.Teacher.Last_Name}}</li>
  {% endfor %}
  <h4>Thursday</h4>
  {% for lect in Thu_lectures %}
  <li>{{lect.get_Time_Slot_display}} | {{lect.Course.Name}} | {{lect.Venue}} | {{lect.Teacher.Designation}} {{lect.Teacher.First_Name}} {{lect.Teacher.Last_Name}}</li>
  {% endfor %}
  <h4>Friday</h4>
  {% for lect in Fri_lectures %}
  <li>{{lect.get_Time_Slot_display}} | {{lect.Course.Name}} | {{lect.Venue}} | {{lect.Teacher.Designation}} {{lect.Teacher.First_Name}} {{lect.Teacher.Last_Name}}</li>
  {% endfor %}


  </ul>

{% endblock %}

TimeTable/management/templates/management/timetable2.html
{% extends 'management/base.html' %}
{% block title%}Student TimeTable{%endblock%}
{% block body %}
  <h1>Welcome to the PEC TimeTable Management System!</h1>

  <h2>{{name}}</h2>
  <h4>Student ID : {{student.Student_ID}}</h4>
  <h4>Programme  : {{student.Programme}}</h4>
  <h4>Year       : {{student.Year}}</h4>
  <h4>Branch     : {{student.Department}}</h4>

  <ul>
  <h3><a href = "/management/student/{{student.Student_ID}}/">Hide TimeTable</a></h3>
  <h1>Time Table</h1>
  <h4>Monday</h4>

  <table class="table">

  <thead>
    <tr>
      <th>Day</th>
      <th>Time Slot</th>
      <th>Course</th>
      <th>Venue</th>
      <th>Taught By</th>
    </tr>
    </thead>
    <tbody>
      {% for lect in all_lectures %}
      <tr>
        <td>{{lect.get_Day_display}}</td>
        <td>{{lect.get_Time_Slot_display}}</td>
        <td>{{lect.Course.Name}}</td>
        <td>{{lect.Venue}}</td>
        <td>{{lect.Teacher.Designation}} {{lect.Teacher.First_Name}} {{lect.Teacher.Last_Name}}</td>
      </tr>
      {% endfor %}
    </tbody>

  </table>

  <h4>Tuesday</h4>
  <table class="table">

  <thead>
    <tr>
      <th>Time Slot</th>
      <th>Course</th>
      <th>Venue</th>
      <th>Taught By</th>
    </tr>
    </thead>
    <tbody>
      {% for lect in Tue_lectures %}
      <tr>
        <td>{{lect.get_Time_Slot_display}}</td>
        <td>{{lect.Course.Name}}</td>
        <td>{{lect.Venue}}</td>
        <td>{{lect.Teacher.Designation}} {{lect.Teacher.First_Name}} {{lect.Teacher.Last_Name}}</td>
      </tr>
      {% endfor %}
    </tbody>

  </table>

  <h4>Wednesday</h4>
  <table class="table">

  <thead>
    <tr>
      <th>Time Slot</th>
      <th>Course</th>
      <th>Venue</th>
      <th>Taught By</th>
    </tr>
    </thead>
    <tbody>
      {% for lect in Wed_lectures %}
      <tr>
        <td>{{lect.get_Time_Slot_display}}</td>
        <td>{{lect.Course.Name}}</td>
        <td>{{lect.Venue}}</td>
        <td>{{lect.Teacher.Designation}} {{lect.Teacher.First_Name}} {{lect.Teacher.Last_Name}}</td>
      </tr>
      {% endfor %}
    </tbody>

  </table>

  <h4>Thursday</h4>
  <table class="table">

  <thead>
    <tr>
      <th>Time Slot</th>
      <th>Course</th>
      <th>Venue</th>
      <th>Taught By</th>
    </tr>
    </thead>
    <tbody>
      {% for lect in Thu_lectures %}
      <tr>
        <td>{{lect.get_Time_Slot_display}}</td>
        <td>{{lect.Course.Name}}</td>
        <td>{{lect.Venue}}</td>
        <td>{{lect.Teacher.Designation}} {{lect.Teacher.First_Name}} {{lect.Teacher.Last_Name}}</td>
      </tr>
      {% endfor %}
    </tbody>

  </table>

  <h4>Friday</h4>
  <table class="table">

  <thead>
    <tr>
      <th>Time Slot</th>
      <th>Course</th>
      <th>Venue</th>
      <th>Taught By</th>
    </tr>
    </thead>
    <tbody>
      {% for lect in Fri_lectures %}
      <tr>
        <td>{{lect.get_Time_Slot_display}}</td>
        <td>{{lect.Course.Name}}</td>
        <td>{{lect.Venue}}</td>
        <td>{{lect.Teacher.Designation}} {{lect.Teacher.First_Name}} {{lect.Teacher.Last_Name}}</td>
      </tr>
      {% endfor %}
    </tbody>

  </table>



  </ul>
{% endblock %}